apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-python-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-python-example
    app.kubernetes.io/part-of: rhtap-python-example
  name: rhtap-python-example
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: rhtap-python-example
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: rhtap-python-example
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rycole-tenant/rhtap-python-example/rhtap-python-example@sha256:5639c8f3fef0b18522db833ce6d626fb04dd10d93e081a200160a2f249d76e66
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
