apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-python-example
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rycole-tenant/rhtap-python-example/rhtap-python-example@sha256:5639c8f3fef0b18522db833ce6d626fb04dd10d93e081a200160a2f249d76e66
        name: my-python
        resources: {}
status: {}
